<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions" Version="8.10.0" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.9" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
        <PackageReference Include="StrawberryShake.Server" Version="16.3.0" />
        <PackageReference Include="Testcontainers.Kafka" Version="4.12.0" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="xunit.runner.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <GraphQL Update="GraphQL\Categories\SaveCategory\saveCategory.graphql">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </GraphQL>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Codeflix.Catalog.Api\Codeflix.Catalog.Api.csproj"/>
        <ProjectReference Include="..\..\src\Codeflix.Catalog.Infra.Messaging\Codeflix.Catalog.Infra.Messaging.csproj"/>
        <ProjectReference Include="..\Codeflix.Catalog.Tests.Shared\Codeflix.Catalog.Tests.Shared.csproj"/>
    </ItemGroup>

</Project>
