<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HotChocolate.AspNetCore" Version="16.3.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Codeflix.Catalog.Application\Codeflix.Catalog.Application.csproj" />
      <ProjectReference Include="..\Codeflix.Catalog.Infra.Data.ES\Codeflix.Catalog.Infra.Data.ES.csproj" />
      <ProjectReference Include="..\Codeflix.Catalog.Infra.Messaging\Codeflix.Catalog.Infra.Messaging.csproj" />
    </ItemGroup>

</Project>
