<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Codeflix.Catalog.Application\Codeflix.Catalog.Application.csproj" />
      <ProjectReference Include="..\..\src\Codeflix.Catalog.Infra.Data.ES\Codeflix.Catalog.Infra.Data.ES.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Bogus" Version="35.6.3" />
    </ItemGroup>

</Project>
