<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Devflix.Content.Admin.Application\Devflix.Content.Admin.Application.csproj" />
    <ProjectReference Include="..\Devflix.Content.Admin.Domain\Devflix.Content.Admin.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.EntityFrameworkCore.Relational">
      <HintPath>..\..\..\..\..\.packages\NuGet\cache\microsoft.entityframeworkcore.relational\9.0.4\lib\net8.0\Microsoft.EntityFrameworkCore.Relational.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
