### POST Create connector
POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name": "content-admin",
  "config": {
    "name": "content-admin",
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "tasks.max": "1",
    "database.hostname": "devflix.content.admin.db",
    "database.port": "3306",
    "database.user": "root",
    "database.password": "root",
    "database.server.id": "184054",
    "topic.prefix": "contentadmin",
    "database.include.list": "content",
    "schema.history.internal.kafka.bootstrap.servers": "kafka:29092",
    "schema.history.internal.kafka.topic": "schema-changes.content.admin.admin",
    "snapshot.mode": "when_needed",
    "tombstones.on.delete": false
  }
}

### PUT Update connector
PUT http://localhost:8083/connectors
Content-Type: application/json

{
  "name": "content-admin",
  "connector.class": "io.debezium.connector.mysql.MySqlConnector",
  "tasks.max": "1",
  "database.hostname": "devflix.content.admin.db",
  "database.port": "3306",
  "database.user": "root",
  "database.password": "root",
  "database.server.id": "184054",
  "topic.prefix": "contentadmin",
  "database.include.list": "content",
  "schema.history.internal.kafka.bootstrap.servers": "kafka:29092",
  "schema.history.internal.kafka.topic": "schema-changes.content.admin",
  "snapshot.mode": "when_needed",
  "tombstones.on.delete": false
}

### DELETE Delete connector
DELETE http://localhost:8083/connectors/content-admin

### PUT Validate Config
PUT http://localhost:8083/connector-plugins/MySqlConnector/config/validate
Content-Type: application/json

{
  "name": "content-admin",
  "connector.class": "io.debezium.connector.mysql.MySqlConnector",
  "tasks.max": "1",
  "database.hostname": "devflix.content.admin.db",
  "database.port": "3306",
  "database.user": "root",
  "database.password": "root",
  "database.server.id": "184054",
  "topic.prefix": "contentadmin",
  "database.include.list": "content",
  "schema.history.internal.kafka.bootstrap.servers": "kafka:29092",
  "schema.history.internal.kafka.topic": "schema-changes.content.admin",
  "snapshot.mode": "when_needed",
  "tombstones.on.delete": false
}